version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo_user:mongo_pass@mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
